### ISSUE TITLE
Subject alternative name extension must be marked critical if the "subject" field is empty

### ISSUE THREAD

**Issue by fiveoclock** [smallstep/certificates#302] opened 2020-06-25 16:32 UTC
### Subject of the issue
Subject alternative name extension must be marked critical if the "subject" field is empty according to RFC 5280

Source https://tools.ietf.org/html/rfc5280#section-4.1.2.6 :
   If subject naming information is present only in the subjectAltName extension
   (e.g., a key bound only to an email address or URI), then the subject
   name MUST be an empty sequence and the subjectAltName extension MUST
   be critical.

and again later https://tools.ietf.org/html/rfc5280#section-4.2.1.6 :
   Further, if the only subject identity included in the certificate is
   an alternative name form (e.g., an electronic mail address), then the
   subject distinguished name MUST be empty (an empty sequence), and the
   subjectAltName extension MUST be present.  If the subject field
   contains an empty sequence, then the issuing CA MUST include a
   subjectAltName extension that is marked as critical.

### Background
I'm using cert-manager (v0.15.1) with ingress-shim to automatically retrieve certificates from Step-CA using the ACME provisioner. The certificates received certificates work well in Firefox and on Windows, but MacOS (Chrome and Safari) complains with the message "Certificate not standards compliant" but doesn't give any additional hints why it thinks so. The chain is trusted btw. it's just the leaf certificate.

When inspecting the certificate I saw that the Subject is empty with only the subject alternative name set. In the RFC I found out that the subject alternative name extension must be marked 'critical' if the 'subject' field is empty. Therefore I assume that might be the reason why MacOS doesn't accept the certificate as valid.

### Your environment
* OS - Step CA in Docker
* Version - Smallstep CA/0.14.4 (linux/amd64) Release Date: 2020-05-01 01:58 UTC

### Steps to reproduce
* Create a custom Issuer / ClusterIssuer pointing to Step-CA
* Create a Kubernetes Ingress with using the required annotations for cert-manager
* Inspect the signed certificate after it was retrieved - check if the subject alternative name is marked 'critical' or not

### Expected behaviour
The subject alternative name should be marked 'critical' when the 'subject' field is empty. 
An alternative (less favourable) solution would be to add the first SAN as subject.

### Actual behaviour
The 'subject' field is empty and the subject alternative name is marked as 'not critical' which does not comply with RFC 5280.

### Additional context
Somhow related to this issue:

Disable the need for CN in Subject of Certificate Signing Requests (CSR) #226
https://github.com/smallstep/certificates/issues/226

![cert1](https://user-images.githubusercontent.com/318735/85760547-3b46a000-b712-11ea-80f6-292870017ce7.png)

**Comment by dopey** [comment] 2020-06-25 18:59
Interesting! Our `csr` generation code always sets a Subject attribute so we've run into various side effects of this "bug" before. The last time we ran into this was our "certificate inspection" code assumed that every cert had a Subject and would munge the output if one wasn't present.

Anyhow, cool! This is definitely a bug. We'll triage it and it'll probably fall into a sprint in the short term.

**Comment by fiveoclock** [comment] 2020-06-25 20:22
Thank you for your reply! 

From what I read putting the first SAN into the Common Name is also the best solution as the common name can only be 64 bytes long.

I'm posting the Certificate Customer Ressource Defintion, Certificate Request and resulting Certificate. Maybe it help you to track the issue.. 

The certificate request (generated by cert-manager ingres-shim):
```
kind: Certificate
apiVersion: cert-manager.io/v1alpha2
metadata:
  creationTimestamp: '2020-06-23T17:49:11Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-9.3.14
    io.cattle.field/appId: wordpress
  name: blog.zoo-tst.mmx.mmdom.net-tls
  namespace: wordpress
  ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: wordpress
      uid: 880e778f-8021-4789-a1ec-fad37a312013
  resourceVersion: '24181810'
  selfLink: >-
    /apis/cert-manager.io/v1alpha2/namespaces/wordpress/certificates/blog.zoo-tst.mmx.mmdom.net-tls
  uid: bc71df18-ab19-43f5-b9e9-39d24de375f1
spec:
  dnsNames:
    - blog.zoo-tst.mmx.mmdom.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: mm-acme
  secretName: blog.zoo-tst.mmx.mmdom.net-tls
status:
  conditions:
    - lastTransitionTime: '2020-06-23T17:50:58Z'
      message: Certificate is up to date and has not expired
      reason: Ready
      status: 'True'
      type: Ready
  notAfter: '2020-06-27T17:50:58Z'
```

The Certificate request (as i understand this is also generated by cert-manager ingres-shim) (copied the csr-string from the Custom Ressource Definition, then base64 decodeded it):
```
# openssl req  -in file.txt -text -noout
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject:
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a0:d7:ba:a7:4d:c0:e9:36:20:92:e9:18:bd:d3:
                    95:bd:cd:e7:4a:a0:75:19:3a:21:a2:22:56:b3:1f:
                    b4:7f:e6:82:14:d0:94:4e:83:84:f0:43:17:d8:50:
                    9e:19:f4:fd:2a:93:66:24:59:fc:1c:99:7c:bd:2e:
                    cb:90:9b:eb:72:8f:83:99:aa:7a:18:6f:35:0e:e4:
                    33:1f:f5:d5:59:bc:bf:5b:6b:32:04:5d:a0:0b:c2:
                    90:47:86:bf:f5:43:29:bd:d5:5b:df:a7:19:fc:bf:
                    67:12:91:37:ba:ef:d6:58:9e:e5:1d:75:5a:38:76:
                    0d:d4:54:9c:c7:8d:ca:28:76:50:a9:ab:ee:42:dc:
                    02:cb:b9:a8:45:fe:c0:fb:21:48:1b:7f:0f:f5:8c:
                    d5:c1:80:32:49:65:5a:24:af:82:c4:59:70:c2:a4:
                    54:25:47:e0:e8:bd:6a:02:21:7b:af:83:6d:d2:04:
                    a1:7f:60:36:b1:72:e1:33:56:f1:86:da:77:9f:69:
                    1b:16:21:78:1a:4d:b8:b1:b2:a2:ab:c2:64:82:e4:
                    33:2b:2f:c4:8a:b4:2d:7d:33:a0:19:20:8e:c0:6a:
                    da:e3:a9:8c:ee:29:ad:ef:fc:24:da:9b:08:9b:88:
                    02:4b:ff:fb:f5:24:81:4d:6e:0e:56:6d:48:18:c8:
                    9f:0f
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:blog.zoo-tst.mmx.mmdom.net
    Signature Algorithm: sha256WithRSAEncryption
         6e:11:54:cb:20:7e:04:ba:27:a1:03:62:56:0c:6f:e4:68:77:
         a9:00:e2:51:88:b8:b6:47:e6:75:99:e4:d5:d6:03:16:71:aa:
         b8:6f:56:91:02:49:a2:30:2b:a8:77:1a:6e:8e:88:0e:f1:dc:
         3d:51:30:20:11:b4:22:ef:02:e3:77:ef:40:5f:ab:e2:d2:a8:
         a9:a0:95:0d:70:e1:c5:2e:ac:66:dc:bd:1e:19:6e:a9:ba:01:
         1b:0a:79:87:87:86:44:31:bd:03:66:34:95:69:8d:e0:93:38:
         1d:2a:3e:79:a6:2d:87:70:7a:7d:f5:83:96:6a:fc:9d:d8:ac:
         af:99:41:1c:57:92:e7:17:9b:a2:66:6d:9e:be:ae:59:db:b9:
         4a:40:cd:f4:91:d0:26:b1:17:87:70:7a:06:9f:4c:d8:af:a1:
         30:04:b1:2e:b2:d7:1a:31:94:df:09:0e:23:d4:d9:e9:64:25:
         65:89:fe:6f:5b:e8:22:e6:2f:76:5b:ee:60:5f:95:84:27:d5:
         f8:19:60:c1:bd:c3:9d:06:a9:5a:ba:70:e4:2b:71:49:d4:81:
         53:f6:30:fd:fb:c5:eb:d8:3f:ab:b1:80:73:c0:12:86:80:3c:
         9b:42:48:59:00:78:c3:44:db:1d:41:61:ca:b6:3f:85:a6:28:
         89:84:2c:34
```

The resulting certificate:
```
# openssl x509 -in  blog.crt  -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            63:a0:b4:3b:8e:5a:26:a8:c1:b7:2b:ee:b8:67:c7:88
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Mayr-Melnhof ACME-v1
        Validity
            Not Before: Jun 23 17:49:58 2020 GMT
            Not After : Jun 27 17:50:58 2020 GMT
        Subject:
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a0:d7:ba:a7:4d:c0:e9:36:20:92:e9:18:bd:d3:
                    95:bd:cd:e7:4a:a0:75:19:3a:21:a2:22:56:b3:1f:
                    b4:7f:e6:82:14:d0:94:4e:83:84:f0:43:17:d8:50:
                    9e:19:f4:fd:2a:93:66:24:59:fc:1c:99:7c:bd:2e:
                    cb:90:9b:eb:72:8f:83:99:aa:7a:18:6f:35:0e:e4:
                    33:1f:f5:d5:59:bc:bf:5b:6b:32:04:5d:a0:0b:c2:
                    90:47:86:bf:f5:43:29:bd:d5:5b:df:a7:19:fc:bf:
                    67:12:91:37:ba:ef:d6:58:9e:e5:1d:75:5a:38:76:
                    0d:d4:54:9c:c7:8d:ca:28:76:50:a9:ab:ee:42:dc:
                    02:cb:b9:a8:45:fe:c0:fb:21:48:1b:7f:0f:f5:8c:
                    d5:c1:80:32:49:65:5a:24:af:82:c4:59:70:c2:a4:
                    54:25:47:e0:e8:bd:6a:02:21:7b:af:83:6d:d2:04:
                    a1:7f:60:36:b1:72:e1:33:56:f1:86:da:77:9f:69:
                    1b:16:21:78:1a:4d:b8:b1:b2:a2:ab:c2:64:82:e4:
                    33:2b:2f:c4:8a:b4:2d:7d:33:a0:19:20:8e:c0:6a:
                    da:e3:a9:8c:ee:29:ad:ef:fc:24:da:9b:08:9b:88:
                    02:4b:ff:fb:f5:24:81:4d:6e:0e:56:6d:48:18:c8:
                    9f:0f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier:
                42:87:A4:6C:49:35:44:AF:F4:BF:D0:20:9F:E4:C7:FB:A5:28:27:FB
            X509v3 Authority Key Identifier:
                keyid:FB:62:3D:F0:56:B9:DD:EF:6D:9E:1F:40:33:1E:CF:60:D6:12:C9:AC

            X509v3 Subject Alternative Name:
                DNS:blog.zoo-tst.mmx.mmdom.net
            1.3.6.1.4.1.37476.9000.64.1:
                0......acme..
    Signature Algorithm: sha256WithRSAEncryption
         48:c4:3b:62:a5:1a:62:7e:e5:9d:f4:e4:60:e8:43:4b:56:93:
....
```

**Comment by tinkivity** [comment] 2020-07-10 09:00
I am actually very glad to find this bug ticket. I installed version 0.14.4 (linux/amd64) in the first week of June and spent a couple of days trying to figure out what I am doing wrong, but found no hint on what exactly is "not standards compliant" with the certificate. Finally, this ticket answers what's wrong. Just for reference I will attach a screenshot of my problem.

<img width="525" alt="Screen Shot 2020-07-10 at 10 39 10 AM" src="https://user-images.githubusercontent.com/30754617/87136828-52ea6080-c29c-11ea-979f-6a6d525af68f.png">

**Comment by dopey** [comment] 2020-07-10 17:17
@tinkivity thanks for confirming!

Would you folks mind testing with the most recent version of certificates (0.14.6). I have a theory that this might be fixed. I've tested by jimmying the code and explicitly setting the Subject in the template to be empty right before signing (and it worked, I got critical SANs extensions), but I haven't tested with `cert-manager`.

If you're already on the most recent version then my theory is wrong and that would be helpful to know too :)

**Comment by andrewying** [comment] 2020-07-11 09:31
Thanks, upgraded to version `0.14.6` of the `smallstep/step-ca` docker image, and it's now working on there!

![Screenshot 2020-07-11 at 10 22 44 am](https://user-images.githubusercontent.com/1071082/87221032-e4bba180-c360-11ea-85b2-796160e5fddd.png)

Indeed SAN is now marked as critical.

![Screenshot 2020-07-11 at 10 30 04 am](https://user-images.githubusercontent.com/1071082/87221150-ac689300-c361-11ea-9455-d4e5b4aa1493.png)

**Comment by fiveoclock** [comment] 2020-07-13 08:23
Just tested with step-ca docker image version 0.14.6 and I can confirm too that the SAN is now marked as critical. Also MacOS now recognises the certificates as valid.

Thank you for your work :)

**Comment by dopey** [comment] 2020-07-13 17:07
Nice! Glad to hear it. Thanks for taking the time to test. I'll close this issue, but please let me know if there's a regression.

**Comment by mholt** [comment] 2020-08-20 20:58
@dopey I'm getting this again in v0.15.0. Seems to be the same problem, SAN is not critical. Should I open new issue?

<img width="713" alt="Screen Shot 2020-08-20 at 2 57 41 PM" src="https://user-images.githubusercontent.com/1128849/90824990-871e5b80-e2f5-11ea-88a2-13e9513db4b4.png">

**Comment by dopey** [comment] 2020-08-20 21:14
Nope. Re-opening until we figure it out. Thanks for bringing to our attention.

**Comment by mholt** [comment] 2020-08-20 21:15
Thanks! If it helps, the code I'm using to generate the cert is here: https://github.com/caddyserver/caddy/blob/0279a57ac465b2920abf71d86203d9feac2015b5/modules/caddytls/internalissuer.go#L123

With the exception that `profileDefaultDuration` is replaced with this type for the v0.15.0 compatibility:

```go
// customCertLifetime allows us to customize certificates that are issued
// by Smallstep libs, particularly the NotBefore & NotAfter dates.
type customCertLifetime time.Duration

func (d customCertLifetime) Modify(cert *x509.Certificate, _ provisioner.SignOptions) error {
	cert.NotBefore = time.Now()
	cert.NotAfter = cert.NotBefore.Add(time.Duration(d))
	return nil
}
```

(If you need to see the CA side of things, it's here: https://github.com/caddyserver/caddy/blob/0279a57ac465b2920abf71d86203d9feac2015b5/modules/caddypki/ca.go)

**Comment by maraino** [comment] 2020-08-20 22:25
@mholt I know what's going on, with certificate templates, we don't create a template directly from the CSR (unless you want to), and as you are not passing any option with a template, it just creates a template from the incoming CSR, that has the Critical value set to false. 

We can fix the certificate template created this way and set the critical to true if no templates are being used.

**Comment by maraino** [comment] 2020-08-20 22:57
Reopening, we need to update dependencies in certificates.

**Closed** 2020-08-20 23:03 UTC
Labels: bug, cert-flex
