### ISSUE TITLE
Sign ssh certificates with more modern algorithm

### ISSUE THREAD

**Issue by glance-** [smallstep/certificates#581] opened 2021-05-20 09:30 UTC
### What would you like to be added
Step should by default use more modern signature algorims than ssh-rsa, but could be in some cases told to issue a certificate with a legacy signature. rsa-sha2-256 is supported since OpenSSH 7.2 which covers most distros, so legacy support is according to me optional. See [2] for a quick example on how this was fixed in vault.

### Why this is needed
Since version 8.2 of openssh the ssh-rsa algorithm is considered insecure and has been removed [2]

[1] https://github.com/hashicorp/vault/pull/8383
[2] https://www.openssh.com/txt/release-8.2

**Comment by maraino** [comment] 2021-05-20 19:26
To clarify this issue, by default, `step` + `step-ca` will create certificates using ecdsa+sha256 (`ecdsa-sha2-nistp256-cert-v01`). But if an RSA key is signed (`step ssh certificate --sign mariano@smallstep.com rsa.pub`) then yes, we should not use the current default of Go.

**Comment by glance-** [comment] 2021-05-24 21:46
We're using sshagentkms with a gpg-agent backed by a yubikey for our CA key store, and that's why we're running with rsa-keys.

**Comment by dopey** [comment] 2021-05-25 17:20
https://github.com/smallstep/cli/issues/477

Closing because this is a duplicate of the above issue ^.

**Closed by dopey** 2021-05-25 17:20 UTC
Labels: enhancement, needs triage
