### ISSUE TITLE
[Bug]: step-ca setup fails on vanilla Fedora with moby-engine (Docker) container

### ISSUE THREAD

**Issue by rungitringit** [smallstep/certificates#961] opened 2022-06-18 10:26 UTC
### Steps to Reproduce

I'm unable to complete step-ca setup when running a container using Docker from Fedora Linux.  I'm sure I'm not doing anything stupid, but the container doesn't respond on port 9000 from localhost while trying to finish setup.

I've tried this multiple times and different ways but always get the same result.  When re-attempting I've completely purged everything, including the container image, to ensure a clean start.

### Your Environment

* OS - Fedora 35 (fully patched)
* `step-ca` Version - 0.20.0
* moby-engine 20.10.16-1 (an Open-Source Docker fork)

### Expected Behavior

`smallstep/step-ca` container responds to a localhost request on port 9000 after the first configuration step is completed and the container has been started.

### Actual Behavior

Following both the Quickstart and Manual Installation from the documentation [1] I am always stuck on the setup step here:

```
{
  CA_FINGERPRINT=$(docker run -v step:/home/step smallstep/step-ca step certificate fingerprint certs/root_ca.crt)
  step ca bootstrap --ca-url https://localhost:9000 --fingerprint $CA_FINGERPRINT
}
```
as it always returns: `read: connection reset by peer`.

curl returns:
```
# curl https://localhost:9000
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9000
```
This reads like an instant denial from a firewall, but I'm trying to connect on localhost and the container does appear to be listening on port 9000.

``` 
docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED          STATUS                      PORTS                    NAMES
c6f438d7e4cf   smallstep/step-ca   "/bin/bash /entrypoi…"   22 minutes ago   Up 22 minutes (unhealthy)   0.0.0.0:9000->9000/tcp   brave_napier
```
```
# ss -plant | grep 9000
LISTEN 0      4096                0.0.0.0:9000               0.0.0.0:*     users:(("docker-proxy",pid=3552,fd=4))
```

[1] https://smallstep.com/docs/tutorials/docker-tls-certificate-authority/#manual-installation

### Additional Context

There are no errors from the container itself either:
```# docker run  -p 9000:9000 -v step:/home/step smallstep/step-ca
badger 2022/06/18 09:51:38 INFO: All 1 tables opened in 0s
badger 2022/06/18 09:51:38 INFO: Replaying file id: 0 at offset: 2809
badger 2022/06/18 09:51:38 INFO: Replay took: 9.417µs
2022/06/18 09:51:38 Starting Smallstep CA/0.20.0 (linux/amd64)
2022/06/18 09:51:38 Documentation: https://u.step.sm/docs/ca
2022/06/18 09:51:38 Community Discord: https://u.step.sm/discord
2022/06/18 09:51:38 Config file: /home/step/config/ca.json
2022/06/18 09:51:38 The primary server URL is https://172.16.16.6:10443
2022/06/18 09:51:38 Root certificates are available at https://172.16.16.6:10443/roots.pem
2022/06/18 09:51:38 Additional configured hostnames: ca.home.test
2022/06/18 09:51:38 X.509 Root Fingerprint: <afingerprinthere>
2022/06/18 09:51:38 Serving HTTPS on :10443 ...
```
The output stays on that and no errors are record.

Note that 172.16.16.0/24 is the subnet this Fedora system is running on.  There's no IP or network conflicts with the random networks used by Docker/Moby.  From `docker network inspect bridge`
```
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
```

There are no other errors I can find in system logs and there are no SELinux denials.

### Contributing

Vote on this issue by adding a 👍 reaction.

**Comment by jdoss** [comment] 2022-06-22 22:17
Hey @rungitringit I was not able to reproduce this with Fedora 36 using Podman, which I admit is not exactly the same setup as you. 

The one thing that seems to stick out in your bug report is this:

```
2022/06/18 09:51:38 Serving HTTPS on :10443 ...
```

It looks like your step-ca instance is running on a different port inside the container. Here is my logs from my test:

```
$ podman logs step-ca

*snip*
badger 2022/06/22 21:47:01 INFO: All 0 tables opened in 0s
2022/06/22 21:47:01 Starting Smallstep CA/0.20.0 (linux/amd64)
2022/06/22 21:47:01 Documentation: https://u.step.sm/docs/ca
2022/06/22 21:47:01 Community Discord: https://u.step.sm/discord
2022/06/22 21:47:01 Config file: /home/step/config/ca.json
2022/06/22 21:47:01 The primary server URL is https://testing.quickvm.com:9000
2022/06/22 21:47:01 Root certificates are available at https://testing.quickvm.com:9000/roots.pem
2022/06/22 21:47:01 Additional configured hostnames: localhost, sw-0608
2022/06/22 21:47:01 X.509 Root Fingerprint: 3550253567febf5e1cccc107d7b321ec8aaa28000f03cbf2a5502c25c3ad56d3
2022/06/22 21:47:01 Serving HTTPS on :9000 ...
time="2022-06-22T21:52:40Z" level=info duration="130.577µs" duration-ns=130577 fields.time="2022-06-22T21:52:40Z" method=GET name=ca path=/root/3550253567febf5e1cccc107d7b321ec8aaa28000f03cbf2a5502c25c3ad56d3 protocol=HTTP/2.0 referer= remote-address=10.0.2.100 request-id=capoua7a4ba9feafkrfg size=640 status=200 user-agent="Smallstep CLI/0.20.0 (linux/amd64)" user-id=
2022/06/22 21:53:04 /usr/local/go/src/net/http/server.go:3195: http: TLS handshake error from 10.0.2.100:51346: local error: tls: bad record MAC
time="2022-06-22T21:53:16Z" level=info duration="95.05µs" duration-ns=95050 fields.time="2022-06-22T21:53:16Z" method=GET name=ca path=/health protocol=HTTP/2.0 referer= remote-address=10.0.2.100 request-id=capouj7a4ba9feafkrg0 size=16 status=200 user-agent=curl/7.82.0 user-id=
```

You can see that my step-ca process is running on the default port 9000 but if you do the manual setup in our documentation you can tell it what port you want step-ca to listen on. It writes this configuration to the container volume named `step` and it is mounted to `/home/step` inside the container. If you exec into your running container you can see the configuration files: 

```
$ docker exec -it step-ca bash
bash-5.1$ cd config/
bash-5.1$ pwd
/home/step/config
bash-5.1$ ls -lah
total 8K     
drwx--S---    1 step     step          40 Jun 22 21:47 .
drwxr-sr-x    1 step     step          84 Jun 22 21:52 ..
-rw-r--r--    1 step     step        1.5K Jun 22 21:47 ca.json
-rw-r--r--    1 step     step         217 Jun 22 21:47 defaults.json
```



You can try two things:

Nuke everything and start over
1) Stop the step-ca container
2) Remove the volume `docker volume rm step`
3) Follow the quick start again

or 

Change the port mapping on the container
1) Stop and remove the step-ca container
2) Relaunch and set port with this command 

```
docker run -d -v step:/home/step \
    --name step-ca \
    -p 10443:10443 \
    smallstep/step-ca```
```

Let me know how it goes!

**Comment by tashian** [comment] 2022-06-22 23:21
fwiw, I just tested the tutorial on Darwin w/podman and wasn't able to reproduce this either

**Comment by rungitringit** [comment] 2022-06-23 03:54
@jdoss I think you'll find that the web UI is running at 10443 instead of the default of 443.  That should have nothing to do with the default service on port 9000.


@tashian I appreciate you checking but how is checking podman on Darwin relevant?

I'd love to be using rootless podman nirvana on Fedora but I'm doing this in my home lab and I just don't have the time to deal with additional complexity.  Moby usually just works.

**Comment by rungitringit** [comment] 2022-06-23 03:56
@jdoss yes I think you're mixing up two services.  Please check the latter log I posted.  It includes:
`2022/06/22 21:47:01 Serving HTTPS on :9000 ...`

If there's a misconfiguration here, believe me it's not a trivial one.  It could still be a bug.

**Comment by jdoss** [comment] 2022-06-23 15:22
@rungitringit I do not see any such logs that say you step-ca process is running on `:9000`. 

Did you try my recommendations? Please see my previous response and look at your configuration to see what port you have configured step-ca to run on. The configuration files are in `/home/step/config` on the `step` volume. 

Paste your `defaults.json` and `ca.json` here so we can check them out please.

**Comment by rungitringit** [comment] 2022-06-24 07:41
@jdoss Thank you very much.

> @rungitringit I do not see any such logs that say you step-ca process is running on `:9000`.

Sorry, my mistake!

> Did you try my recommendations?

Yes and the different port mapping did it.  While _a service_ is now running on 10443 I am confused!

I'm trying to run the main UI on a different port as `443` will be used by another service on this system in future.  When answering the setup questions during bootstrapping I changed the port from a displayed default of `443` to `10443`.  So, if the default is shown as `443` where does this port `9000` come from?

As a new person it appeared to be me changing the default web UI from `443` to `10443` while the API or some other interface was hosting on port `9000`, but that doesn't seem to be the case.

Thanks again!

**Comment by rungitringit** [comment] 2022-06-24 09:22
I've just removed everything and started again, going with the prompt 
```
What IP and port will your new CA bind to?
✔ (e.g. :443 or 127.0.0.1:443): 127.0.0.1:443
```
and the same problem happens
```
error downloading root certificate: client.Root; client GET https://localhost:9000/root/<blah> failed: Get "https://localhost:9000/root/<blah>": read tcp 127.0.0.1:60636->127.0.0.1:9000: read: connection reset by peer
```
Could it be that the example port of `443` is the problem and this should be changed to `9000` so that the rest of the instructions work?

**Comment by tashian** [comment] 2022-06-28 15:55
Thanks @rungitringit

I just want to comment on the rationale behind using `curl -k` for the health check.

If the curl call used `--cacert`, then the DNS names on the CA certificate would have to include "localhost" — and that's not necessarily going to be true. I wanted the `curl` to be able to work no matter what DNS names are on the CA certificate.

And, `localhost` connections are already secure. They don't go over a network, so authentication and encryption are unnecessary. There's no leverage point for a man-in-the-middle attack, as far as I know.

**Comment by rungitringit** [comment] 2022-07-09 11:11
> Thanks @rungitringit
> 
> I just want to comment on the rationale behind using `curl -k` for the health check.

Hello, but I added the -k because there were certificate problems, to skip the certificate, noting that doing so was not the point of setting up a CA!.

The instructions do not include that switch.

**Comment by rungitringit** [comment] 2022-07-09 11:22
This may be out of scope to report here in this repo, but the Smallstep docs layout is problematic for me.  I mentioned this briefly in my second-last post above.

Here's a screenshot of the installation guide when displayed on 50% of my screen.  The left half is Firefox, the right two terminals.
Note how the code box is only partly visible?

[screenshot](https://user-images.githubusercontent.com/50512963/178103498-2af08a33-92bd-4035-9ad7-4d49dd9c834f.png)

Also note that the code box does not display what the current version actually shows (I also mentioned this in my 2nd last post).

Thank you

**Comment by jdoss** [comment] 2022-07-11 16:46
@rungitringit Are there any outstanding issues that you need addressed in this ticket? I believe this is not a bug report but a configuration/documentation issue which are better supported on other channels. In the future you can get help via our [GitHub discussions section](https://github.com/smallstep/certificates/discussions) of this repo or on our [Discord](https://u.step.sm/discord).

**Comment by rungitringit** [comment] 2022-07-12 10:02
As I'm on a RH-based system, I've manually copied the `/root/.step/certs/root_ca.crt` to `/etc/pki/ca-trust/source/anchors` as `Smallstep.pem` and run `update-ca-trust` as root.  Now the OS trusts the certificate from localhost:9000.  However these extra steps are not mentioned in the instructions (I just happened to be aware of them) and presumably should not be required.

**Comment by tashian** [comment] 2022-07-12 16:06
Ah yes, I see the issue you're referring to in the instructions @rungitringit.

The issue is that our readme was missing the `--install` flag when running `step ca bootstrap`, to install the root CA cert into the host environment's trust store.

I've fixed that. Thanks for reporting!

**Closed by tashian** 2022-07-12 16:06 UTC
Labels: area/configuration
