### ISSUE TITLE
Add support for multiple intermediate CA

### ISSUE THREAD

**Issue by mattiasvh** [smallstep/certificates#87] opened 2019-08-05 21:23 UTC
### Subject of the improvement
Would it be possible to add support in step ca to create structures of multiple intermediate CAs (case when the path length of the certificate >= 2). It is an idea to change the settings of the lifespan of the created certificates on different Intermediate CAs level.

### Example use case
`Root CA - Intermediate CA 1 - Intermediate CA 2 - leaf certificates`
Intermediate CA2 does not have a constant network connection to Intermediate CA1 (bad network connectivity), so the assumption to use very short lifetimes for passive revocation will introduce issues: due to bad network connectivity it is impossible to do renewal of the certificate in time. To solve this, Intermediate CA 1 would need to issue certificates with a longer lifetime (e.g. multiple years) to Intermediate CA2.
End devices have good network connectivity to Intermediate CA 2, so there shorter lifetimes could be used.

**Comment by mkkeffeler** [comment] 2020-08-17 18:31
is there work planned for this? looks like a lot of community support for this across multiple issues

**Comment by dopey** [comment] 2020-08-17 18:49
Now that this has been unblocked by deploy of cert-flex I'll slap the needs-triage tag on it and we'll review it this week.

**Comment by maraino** [comment] 2020-08-17 19:35
Now that `step` can now create multiple intermediates, it's won't be hard to support a bundle of intermediates in the `crt` field of the ca.json, and append all of them to all the issued certificates. I've just done a small hack on my environment and at least the step-ca certificate works.

**Comment by dopey** [comment] 2020-08-17 19:37
Is there a case to be made for doing this per provisioner? I thought so at first, but now I'm thinking that if you're using the same intermediate to sign them all, they'll probably require the same chain.

**Comment by maraino** [comment] 2020-08-17 19:51
@dopey support for multiple intermediates per provisioner and support a second intermediate ca in step-ca are two different things. 

step-ca with v0.15.0 now supports, with custom templates the issue of `Intermediate CA 2`. But then to have `Intermediate CA 2` sign leaf certificates, we need to bundle `Intermediate CA 2 + Intermediate CA 1` into the leaf certificate, and this is not yet supported, and this is what I'm saying is not hard to add, and I've just added support in my environment, to 1 of the perhaps few places we need to.

**Comment by dopey** [comment] 2020-08-18 18:53
Update here is that the issue is now on our short term roadmap. I can't give a time estimate better than "soon-ish" though.

**Comment by mkkeffeler** [comment] 2020-11-04 20:24
been a minute :) Any info on this feature?

**Comment by alexw19** [comment] 2020-11-05 21:22
Any updates on this feature?

**Comment by maraino** [comment] 2020-11-09 18:43
I added a small update in a duplicated issue https://github.com/smallstep/certificates/issues/244#issuecomment-721964197

> It's not a P0 priority right now, but it's something we will add. The support must be added to both step and step-ca, and the basic building blocks are already in step-ca. We always appreciate contributions to the project.

**Comment by maraino** [comment] 2020-12-29 01:56
Fixed by #440

**Closed by maraino** 2020-12-29 01:56 UTC
Labels: cert-flex, enhancement, roadmap
