### ISSUE TITLE
keep subject cn while adding new domains to an existing certificate via ACME

### ISSUE THREAD

**Issue by DonOtuseGH** [smallstep/certificates#893] opened 2022-04-11 14:09 UTC
### Subject of the issue
subject commonName may change while adding additional domains to an existing certificate via certbot (ACME)

### Your environment
* latest Docker image 
```
smallstep/step-ca    latest       1484a1b3c0c2   5 weeks ago     113MB
```
* Version
```
bash-5.1$ step -v
Smallstep CLI/0.18.2 (linux/amd64)
Release Date: 2022-03-01 23:22 UTC
```

```
# certbot --version
certbot 1.25.0
```

### Steps to reproduce
request certificate via cerbot and verify subject+sans
```
root@ubu2204-vm:~# REQUESTS_CA_BUNDLE=root_ca.crt certbot certonly -n --standalone --expand -d ubu2204-vm.example.com --server https://ca.example.com:9000/acme/acme/directory --agree-tos --email ubu2204-vm@example.com

root@ubu2204-vm:~# openssl x509 -in /etc/letsencrypt/live/ubu2204-vm.example.com/fullchain.pem -noout -subject -ext subjectAltName
subject=CN = ubu2204-vm.example.com
X509v3 Subject Alternative Name:
    DNS:ubu2204-vm.example.com
```

add an additional domain to the existing cert and verify again
```
root@ubu2204-vm:~# REQUESTS_CA_BUNDLE=root_ca.crt certbot certonly -n --standalone --expand -d ubu2204-vm.example.com -d acmeclient.example.com --server https://ca.example.com:9000/acme/acme/directory

root@ubu2204-vm:~# openssl x509 -in /etc/letsencrypt/live/ubu2204-vm.example.com/fullchain.pem -noout -subject -ext subjectAltName
subject=CN = acmeclient.example.com
X509v3 Subject Alternative Name:
    DNS:acmeclient.example.com, DNS:ubu2204-vm.example.com
```

### Expected behaviour
subject commonName should not change in any case (this is how it works e.g. for Let's Encrypt).

### Actual behaviour
subject commonName changes when the additional domain comes before the existing one in alphabetical order.

### Additional context

step-ca logfile shows the correct order in the request, so it should be possible to extract the first domainname before sorting the list of all requested names.

```
step-ca    | time="2022-04-11T15:43:25+02:00" level=info duration=6.683117ms duration-ns=6683117 fields.time="2022-04-11T15:43:25+02:00" method=POST name=ca nonce=QkFFbHE2VUQxbFAzZnVsQTh6WmlzOHBTb0p1NXZkcTM path=/acme/acme/order/yezMuCe5zNhFOzYlxSOfO0JvIcu191C5 protocol=HTTP/1.1 referer= remote-address=1.1.1.1 request-id=c9a30vcnla64v2btlmp0 response="{\"id\":\"yezMuCe5zNhFOzYlxSOfO0JvIcu191C5\",\"status\":\"valid\",\"expires\":\"2022-04-12T13:43:22Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"ubu2204-vm.example.com\"},{\"type\":\"dns\",\"value\":\"acmeclient.example.com\"}],\"notBefore\":\"2022-04-11T13:42:22Z\",\"notAfter\":\"2022-07-10T13:43:22Z\",\"authorizations\":[\"https://ca.example.com:9000/acme/acme/authz/NrXlznuIWfqf42OaKDUpMUlJtFN2BKb5\",\"https://ca.example.com:9000/acme/acme/authz/cOXU9i31PD9VV62KYrLzNGkLpb1YcofR\"],\"finalize\":\"https://ca.example.com:9000/acme/acme/order/yezMuCe5zNhFOzYlxSOfO0JvIcu191C5/finalize\",\"certificate\":\"https://ca.example.com:9000/acme/acme/certificate/pOJuHDWqWffINGgPgX8m0jFPE8ReDcw4\"}" size=704 status=200 user-agent="CertbotACMEClient/1.25.0 (certbot; Ubuntu Jammy Jellyfish (development branch)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.10.4" user-id=
```

**Comment by maraino** [comment] 2022-04-11 19:44
@dopey @hslatman If the RFC allows this, we should also allow it.

@DonOtuseGH Right now I think it would be possible to use [certificate templates](https://smallstep.com/docs/step-ca/templates) to allow this. You should be able to access the CN using `{{ .Insecure.CR.Subject.CommonName }}`.

**Comment by hslatman** [comment] 2022-04-11 20:05
@maraino: I think what's actually going on and described by @DonOtuseGH is that the domain that ends up in the CN changes when a new cert is created using the old cert names as some kind of "template" (but not an actual template). We already allow a CN to be set and also provide a configuration knob to force the first SAN if the CN is not set in the CSR. "Expanding a cert" is not something that's in the ACME RFC; it sounds more like something that certbot provides to make it easier to create a cert for existing domains while adding a new one, instead of creating a totally new one.

@DonOtuseGH: if I understand you correctly, you want `ubu2204-vm.example.com` to remain the CN instead of the new domain when "expanding" the cert. Are you using the `ForceCN / --force-cn` option on the ACME provisioner now? I think what happens is that certbot doesn't provide a CSR with a CN in it for the new cert, but only contains two DNS SANs. The `ForceCN` option then kicks in and picks the first (alphabetical order) DNS SAN, resulting in `acmeclient.example.com` ending up as the CN. If a CSR were provided with `ubu2204-vm.example.com` as the CN, `step-ca` wouldn't change it.

**Comment by DonOtuseGH** [comment] 2022-04-11 21:23
@hslatman you're totally right 😁 I'm using `ForceCN` option in the ACME provisioner config as it seems the certbot CSR doesn't contain a CN in any case, although I found some docs, saying _"When the user invokes certbot with -d, the Common Name field is set to the first domain passed via that argument."_... 🤔 
BTW, the alphabetical order is not only a problem for expanding an existing certificate. I get the same result when I submit both domains at once during the first request.

**Comment by charltonstanley** [comment] 2022-04-12 14:29
Slightly off topic: This issue helped me discover that there was a `ForceCN` option available and it helped explain how it worked. Thank you! I needed this! :smile:

**Comment by DonOtuseGH** [comment] 2022-04-12 23:34
`certbot` keeps all the CSRs locally on the machine (`/etc/letsencrypt/csr/`) so I checked them with `openssl req` and they all have an empty subject. So it looks more like a `certbot` issue...

I tried another ACME client (`uacme`) which works as expected. 👍 

Anyway, thank you very much for your assistance!

**Comment by charltonstanley** [comment] 2022-04-13 01:32
@DonOtuseGH here is why it is missing from `certbot`. `CommonName` is apparently deprecated.

**Comment by charltonstanley** [comment] 2022-04-13 03:04
oops i forgot to paste the link. sorry for the double notification. https://github.com/certbot/certbot/issues/6463#issuecomment-435151087

>Using the common name for this purpose has been deprecated with subject alternative names being the preferred alternative. See https://tools.ietf.org/html/rfc2818#section-3.1.

**Comment by dopey** [comment] 2022-04-13 05:00
Hey, I'm going to close this issue as it appears (unless I've misunderstood) that the behavior has been explained. If I have, in fact, misunderstood, and the issue is not closed, please reopen. Thanks 🍻

**Closed by dopey** 2022-04-13 05:00 UTC
Labels: bug, needs triage

**Comment by DonOtuseGH** [comment] 2022-04-13 08:02
@charltonstanley Thanks for the link, I haven't looked further in the certbot repo yet. I definitely prefer SANs to Subject CN, but unfortunately there are still some legacy apps / use cases that need to be covered as well.

**Comment by hslatman** [comment] 2022-04-13 08:17
I think it would make sense if `certbot` would allow a CN to be set in the CSR. Not as the default, since it's more geared towards general use on the web, but an option to do so is probably good for them to have. This case would strengthen reopening the issue: https://github.com/certbot/certbot/issues/6463#issuecomment-435151087.

That said, we could look into _not_ reordering the SANs in the CSR before it gets made into a certificate, so that when `ForceCN` is active, it'll always be the first SAN that's found in the CSR.
