### ISSUE TITLE
step-ca is hard to configure behind a reverse proxy / load balancer

### ISSUE THREAD

**Issue by jholloway7** [smallstep/certificates#193] opened 2020-02-19 20:45 UTC
### What would you like to be added

step-ca hardwires the host name and port in its ACME directory response. The makes it difficult to configure the server to run behind a reverse proxy or load balancer that is using a different name/port than the first one listed in the step-ca configuration.  

The typical solution is to use the Host header in the HTTP request to return a URL in the same form that was requested by the client.  Some frameworks do validate the Host header against a known list of "valid" domains and return 400 Bad Request if a request makes it to the server with an invalid host name.   

Example:
https://acme.secops-live.local/acme/terraform/directory

If step-ca is configure with dnsNames = [ "localhost", "acme.secops-live.local" ], the response from the directory will contain https://localhost/acme/terraform/...  which isn't reachable by a client that only knows how to reach the directory via https://acme.secops-live.local.

NOTE: This pattern may also affect other HTTP APIs within step-ca outside of the ACME protocol. I do recall having some issues with the step CLI that seemed to be related, but I didn't notice the underlying issue until trying to use it as an ACME provider.

https://github.com/smallstep/certificates/blame/8e882faf44f89178e769cf53923b4db8222bea54/ca/ca.go#L116

I think there may also be some relevant bits in the ACME v2 spec, but I'm not that familiar with JWS to know for sure what they're saying here:

https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.6.4

The workaround is to list the dns name first and to use the standard 443 port.  These options work for my limited use case, but would be fragile in trying to do anything slightly more sophisticated.

### Why this is needed

Most applications these days need the ability to live behind a reverse proxy and/or load balancer to give the deployer options on how to configure their network without directly exposing the application.

Thanks!

**Comment by cpu** [comment] 2020-02-19 20:53
> The typical solution is to use the Host header in the HTTP request to return a URL in the same form that was requested by the client. 

For what it's worth this is the approach Let's Encrypt uses to [generate directory URLs](https://github.com/letsencrypt/boulder/blob/27e785f3f238f4811a44f485c141ac1b925d47cb/web/relative.go#L8-L10) in Boulder (which is deployed behind a reverse proxy).

**Comment by t0xicCode** [comment] 2020-04-12 19:57
To add to this, it's also an issue if you configure step-ca to run on a non-privileged port, then expose a different port to the external network. 

For instance, I have step-ca running in a docker container, and I would like to have it bind to 8443, but then I use docker's expose functionality to bind port 8443 in the container to 443 on the host. Currently, the port used by step-ca inside of the container is hardcoded in the acme responses.

**Comment by fbartels** [comment] 2020-04-20 12:09
In a similar vein I was looking into running step as a ca for ssh login, but the system I wanted to deploy it onto only supports plain http for its reverse proxy.

**Comment by dopey** [comment] 2020-05-04 23:57
> In a similar vein I was looking into running step as a ca for ssh login, but the system I wanted to deploy it onto only supports plain http for its reverse proxy.

@fbartels Would you mind creating a separate issue for this please? We've now heard a few different users ask for a version that doesn't require https, but it would help to get the context of a use case. Also want to be able to track this separately so we can track community support and prioritize accordingly.

**Comment by dopey** [comment] 2020-05-07 21:00
I have a branch that I _think_ is doing relative URL's correctly (or at least better than before). Was wondering if someone with a reverse proxy / load balancer setup handy might test to let me know if this change fixes the issue for them. 

branch: https://github.com/smallstep/certificates/tree/clive-jevons/dynamic-host-detection-for-acme-directory

**Comment by dopey** [comment] 2020-05-15 16:57
Branch merged to master. I'm going to call this issue "done", but feel free to reopen if there's something you feel is missing, etc.

**Closed by dopey** 2020-05-15 16:57 UTC
Labels: area/acme, bug, needs triage

**Comment by mholt** [comment] 2021-07-01 01:36
Thanks for this change. However, while the directory links are right now, it appears to fail JWS verification?

I'm reverse proxying the ACME server using a simple standard proxy:

```go
	targetURL, err := url.Parse("http://localhost:6666")
	if err != nil {
		return err
	}
	proxy := httputil.NewSingleHostReverseProxy(targetURL)
	proxy.ServeHTTP(w, r)
```

I get `urn:ietf:params:acme:error:malformed - The request message was malformed` when the Host header is passed through. The directory links are correct, but new-order shows this "malformed" error message.

If I set `r.Host = localhost:6666` (the internal address) before proxying, the directory links are wrong again of course, and the client can't access the internal address.

Any suggestions? Are you guys using X-Forwarded-For maybe?

**Comment by mholt** [comment] 2021-07-01 19:59
False alarm, the issue is very different from expected. Opened #623 for discussion; though I am not even sure it's a server bug. Just unexpected.

**Comment by Szpark** [comment] 2022-07-01 07:52
@mholt I was finally able to solve it, I shared my working apache conf here: https://github.com/smallstep/certificates/discussions/968
