### ISSUE TITLE
Automatic installation of server as a service.

### ISSUE THREAD

**Issue by AlastairGrowcott** [smallstep/certificates#201] opened 2020-03-03 11:57 UTC
### What would you like to be added
It would be nice if the Ubuntu package, when installed, automatically installed the server as a service, running the "init" step as part of the installer.

### Why this is needed
Convenience. Setting up a systemd service is easy once you know how but can take some time to get exactly right, particularly if you didn't write the server and don't exactly know its dependencies.

**Comment by dcow** [comment] 2020-05-08 03:49
Dupe of https://github.com/smallstep/certificates/issues/122

**Comment by dopey** [comment] 2020-05-27 18:03
I'm going to close this issue since it seems to be a dupe of an existing issue that has a fair bit more conversation. @AlastairGrowcott If you'd like to re-open definitely feel free.

One comment that I'll add, after discussing with the team: 

We're not sure where our package mgmt responsibilities should "end". Should we be providing systemd files for all the different operating systems? There are subtle differences. Managing the systemd files across all the different systems could prove a considerable amount of effort given our small staff. We're definitely fine with hosting example `systemd` files, we're just weary of taking on the responsibility of integrating with more package managers. 

We're integrated with homebrew + AUR(arch) + helm already and nearly every time we release, something breaks downstream because a requirement has changed somewhere. Possibly evidence of a broken release process written mostly by me 🤪.

**Closed by dopey** 2020-05-27 18:03 UTC
Labels: area/CICD, enhancement

**Comment by dcow** [comment] 2020-05-27 21:45
@dopey also might be a reason why many projects include a "source release" and delegate to a package maintainer within the respective communities (Arch, Debian, etc.) to package and release software in the contexts they're most familiar with.
