### ISSUE TITLE
[Docs]: Clarity around policy configuration

### ISSUE THREAD

**Issue by 61131** [smallstep/certificates#1181] opened 2022-11-14 01:47 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to document this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Affected area/feature

I have a newly initialised step CA within a docker container and want to sign a CSR which incorporates a subjectAltName attribute. The documentation of policy rules for provisioners is however unclear with respect to the form and location of policy definition - Compare "Policy in Configuration File" at https://smallstep.com/docs/step-ca/policies with "Example Configuration" at https://smallstep.com/docs/step-ca/configuration. Without such clarity however, signing requests are failing due to invalid URIs - For example:

`$ openssl req -new -key cert.key -out cert.csr -subj "/CN=MyService/" -addext "subjectAltName = URI:urn:example.com:MyService" -addext "KeyUsage = digitalSignature,keyEncipherment,dataEncipherment"`
`$ step ca sign ./cert.csr cert.pem`
`Provisioner: admin (JWK) [kid: UJQ2z_ApR2KAsLcyv64-_h-xRjprNM3DP2VOuwZw4WM]`
`Please enter the password to decrypt the provisioner key: `
`CA: https://localhost:9000`
`The request was forbidden by the certificate authority: certificate request does not contain the valid URIs - got [urn:example.com:MyService], want [].`
`Re-run with STEPDEBUG=1 for more info.`

**Comment by hslatman** [comment] 2022-11-14 09:41
Hi @61131,

Sorry for the confusion. What exactly are you missing? At https://smallstep.com/docs/step-ca/configuration#example-configuration, there's a short example of a policy to prevent the full configuration from becoming too long (see the `policy` under `authority`). At https://smallstep.com/docs/step-ca/policies#policy-in-configuration-file there's a full example, and it's mentioned that it has to go under the `authority` object.

Then back to your error: this particular error is not generated by the policy validator. It's returned by the `urisValidator`, which is used in several provisioners and when checking JWT claims to verify a client is authorized. From your example commands it looks like the CA forbids issuance, because the claims in the one-time token (OTT, a JWT) do not contain the same SANs as in your CSR (generated by `openssl`). In the CLI examples for `step ca sign` the `--token` flag is provided, which is what's missing in your invocation. This is what you need to create a token and to use it:

```console
$ TOKEN=$(step ca token --san urn:example.com:MyService MyService)
$ step ca sign --token $TOKEN ./cert.csr cert.pem
```

The above is a temporary workaround, as there seems to exist a bug in the CLI. When `step ca sign` is invoked with no `--token` provided, it should create the token as part of the flow automatically. You are in fact being prompted for the provisioner password, which is a good sign, but the URIs aren't being merged into the list of SANs that become part of the token, resulting in the issuance being forbidden. I'll fix this 😄

**Comment by hslatman** [comment] 2022-11-14 10:34
The root cause of this issue should be fixed with https://github.com/smallstep/cli/pull/799.

**Comment by 61131** [comment] 2022-11-14 21:38
Hi @hslatman,

Thanks for your prompt and very complete response. 

With regard to inconsistency in policy documentation, I noted that there is a difference in policy definition between https://smallstep.com/docs/step-ca/configuration#example-configuration and https://smallstep.com/docs/step-ca/policies#policy-in-configuration-file. In the former, policies are defined in the following manner:
```
"policy": {
    "x509": {
        "allow": ["*.local"]
    }
```
Whereas in latter, policies are defined in the following manner:
```
"policy": {
    "x509":
        "allow": {
            "dns": ["*.local"],
            "ip": ["192.168.0.0/24"]
        }
```
In any event, I am happy that this request around this use case has identified something that can be worked upon and improved for Smallstep. I have been able to sign the CSR with the workaround that you have described above, but note that I additionally needed to include the subject with the token request and that the generated certificate only included the CommonName attribute of the subject (which while my example above only includes a CommonName attribute, my current use case includes other organisational attributes - I may open another item for this, as while I can "solve" this issue through reducing the attributes that are included in my certificates or employ templates for certificate generation, neither represents an ideal solution).

Thank you again!

**Comment by hslatman** [comment] 2022-11-23 22:05
A PR for our docs repo has been created: https://github.com/smallstep/docs/pull/170.

**Comment by tashian** [comment] 2022-11-23 22:21
The docs have been updated. Thanks @61131 @hslatman

**Closed by tashian** 2022-11-23 22:21 UTC
Labels: needs triage
