### ISSUE TITLE
[Bug]: Docker HSM image can't find correct glibc version

### ISSUE THREAD

**Issue by vitorarins** [smallstep/certificates#1611] opened 2023-11-02 15:41 UTC
### Steps to Reproduce

Running the following command:

```
docker run -it -v step:/home/step \
    -p 9000:9000 \
    -e "DOCKER_STEPCA_INIT_NAME=Smallstep" \
    -e "DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)" \
    -e "DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true" \
    smallstep/step-ca:hsm
 ```

### Your Environment

* OS - Linux/Docker
* `step-ca` Version - from version 0.24.3-rc.2-hsm to 0.25.0-hsm

### Expected Behavior

A common output and a running container:

```
Generating root certificate... done!
Generating intermediate certificate... done!

✔ Root certificate: /home/step/certs/root_ca.crt
✔ Root private key: /home/step/secrets/root_ca_key
✔ Root fingerprint: asdf
✔ Intermediate certificate: /home/step/certs/intermediate_ca.crt
✔ Intermediate private key: /home/step/secrets/intermediate_ca_key
badger 2023/11/02 15:27:37 INFO: All 0 tables opened in 0s
✔ Database folder: /home/step/db
✔ Default configuration: /home/step/config/defaults.json
✔ Certificate Authority configuration: /home/step/config/ca.json
✔ Admin provisioner: admin (JWK)
✔ Super admin subject: step

Your PKI is ready to go. To generate certificates for individual services see 'step help ca'.

FEEDBACK 😍 🍻
  The step utility is not instrumented for usage statistics. It does not phone
  home. But your feedback is extremely valuable. Any information you can provide
  regarding how you’re using `step` helps. Please send us a sentence or two,
  good or bad at feedback@smallstep.com or join GitHub Discussions
  https://github.com/smallstep/certificates/discussions and our Discord 
  https://u.step.sm/discord.

👉 Your CA administrative username is: step
👉 Your CA administrative password is: asdf
🤫 This will only be displayed once.
badger 2023/11/02 15:27:37 INFO: All 0 tables opened in 0s
badger 2023/11/02 15:27:37 INFO: Replaying file id: 0 at offset: 0
badger 2023/11/02 15:27:37 INFO: Replay took: 116.288µs
2023/11/02 15:27:37 Starting Smallstep CA/0.24.3-rc1 (linux/amd64)
2023/11/02 15:27:37 Documentation: https://u.step.sm/docs/ca
2023/11/02 15:27:37 Community Discord: https://u.step.sm/discord
2023/11/02 15:27:37 Config file: /home/step/config/ca.json
2023/11/02 15:27:37 The primary server URL is https://localhost:9000
2023/11/02 15:27:37 Root certificates are available at https://localhost:9000/roots.pem
2023/11/02 15:27:37 Additional configured hostnames: asdf
2023/11/02 15:27:37 X.509 Root Fingerprint: asdf
2023/11/02 15:27:37 Serving HTTPS on :9000 ...
```

### Actual Behavior

Container stops and the output is as following:

```
Generating root certificate... done!
Generating intermediate certificate... done!

✔ Root certificate: /home/step/certs/root_ca.crt
✔ Root private key: /home/step/secrets/root_ca_key
✔ Root fingerprint: asdf
✔ Intermediate certificate: /home/step/certs/intermediate_ca.crt
✔ Intermediate private key: /home/step/secrets/intermediate_ca_key
badger 2023/11/02 15:27:17 INFO: All 0 tables opened in 0s
✔ Database folder: /home/step/db
✔ Default configuration: /home/step/config/defaults.json
✔ Certificate Authority configuration: /home/step/config/ca.json
✔ Admin provisioner: admin (JWK)
✔ Super admin subject: step

Your PKI is ready to go. To generate certificates for individual services see 'step help ca'.

FEEDBACK 😍 🍻
  The step utility is not instrumented for usage statistics. It does not phone
  home. But your feedback is extremely valuable. Any information you can provide
  regarding how you’re using `step` helps. Please send us a sentence or two,
  good or bad at feedback@smallstep.com or join GitHub Discussions
  https://github.com/smallstep/certificates/discussions and our Discord 
  https://u.step.sm/discord.

👉 Your CA administrative username is: step
👉 Your CA administrative password is: asdf
🤫 This will only be displayed once.
/usr/local/bin/step-ca: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/step-ca)
/usr/local/bin/step-ca: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/step-ca)
```

### Additional Context

I tested all image version from 0.24.3-rc.2-hsm to 0.25.0-hsm and they all fail with the same error:
```libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/step-ca)```

Version 0.24.3-rc1-hsm works fine as expected.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment] 2023-11-07 23:40
Hi, the problem is due to the different versions of Debian used for building and running the container. PR #1616 should solve the issue, but a new version will only be available after a new release. 

Once merged, you can build your image with `docker build -f docker/Dockerfile.hsm .`

**Closed** 2023-11-08 00:32 UTC
Labels: bug, needs triage

**Comment by rkgfk** [comment] 2023-11-10 11:14
The same problem exists with the step-kms-plugin. I know it is a different repository. But the current Dockerfile for debian needs to be change to `golang:bullseye` too. It is currently still on `golang`.

**Comment by maraino** [comment] 2023-11-10 23:11
@rkgfk the problem with step-kms-plugin is now fixed:
```console
$ docker run -it smallstep/step-kms-plugin:0.9.2 step-kms-plugin version
Unable to find image 'smallstep/step-kms-plugin:0.9.2' locally
0.9.2: Pulling from smallstep/step-kms-plugin
...
Digest: sha256:08db5168f7dd8eb52ec8eb485e4ddbe0bd76dfe4d04b14e8baf0ddf880689609
Status: Downloaded newer image for smallstep/step-kms-plugin:0.9.2
step-kms-plugin/0.9.2 (linux/amd64)
Release Date: 2023-11-10 22:18 UTC
```

**Comment by Thisora** [comment] 2024-01-11 08:08
Is that possible to update image smallstep/step-ca-hsm on docker-hub with this fix ?
