### ISSUE TITLE
is it possible that a provisioner signs for another sub ca?

### ISSUE THREAD

**Issue by oli4435** [smallstep/certificates#163] opened 2020-01-26 18:07 UTC
Hello, 

thirst of all: great project - thanks for you work!

I went through the docs but didn't find a solution for my usecase.

I've created another intermediate ca - let's say for client cert auths. Is it possible that I create a new provisioner and he's allowed to create certs signed by this new CA?

After looking into the ca.json I assume this is not possible because the "default" intermediate ca is put in the default section and not to a provisioner.

Is there an enhancement planned to this?
Also to split profiles for Web Server Authentication and TLS Web Client Authentication would be great.

Cheers!

**Comment by mmalone** [comment] 2020-01-27 22:00
An instance of `step-ca` can only sign certificates with a single signing key at the moment. You'd need to run a second instance of `step-ca` with your second intermediate.

Regarding profiles for server / client, we'll be a lot closer to supporting that at the CA once we have better profile support in the `step` client. There's an issue for that here: https://github.com/smallstep/cli/issues/110

**Comment by dopey** [comment] 2020-01-28 00:10
Hey @oli4435, thanks for opening up the issue! And glad you're finding the project useful.

This is a great question. As you guessed from the docs and the `ca.json`, unfortunately this feature/ability is not possible at this time. There is only one signer for tls certificates (the intermediate certificate) per instance of `step-ca`. That said, this is not the first time we've heard this request and we'll definitely discuss it during out next planning meeting. 

For now, our recommendation is to run multiple instances of the `step-ca`. So if you want different signers for clients and servers, then you'd probably run two instances of the `step-ca`. You can actually generate one PKI (root + intermediate) and then use that same root to generate subsequent PKIs (using `step ca init --root <cert> --key <priv>`).

Let me know if you have any questions about that.

**Comment by dopey** [comment] 2020-04-15 16:20
Closing as duplicate of of https://github.com/smallstep/certificates/issues/186.

**Closed by dopey** 2020-04-15 16:20 UTC
Labels: area/X509, enhancement
