### ISSUE TITLE
[Bug]: step-ca does not detect when it's not in an interactive shell, sends escape codes for colours regardless

### ISSUE THREAD

**Issue by cricalix** [smallstep/certificates#1549] opened 2023-09-24 06:24 UTC
### Steps to Reproduce

Run step-ca docker image on something like a Synology NAS, which provides a web UI to review the logs.

![image](https://github.com/smallstep/certificates/assets/1478917/cd9de2f6-3a59-4bd4-ba3d-4c65e93c3e68)

### Your Environment

* OS - Synology host, Docker image pulled as :latest on 2023-09-23
* `step-ca` Version - 24.2

### Expected Behavior

step-ca detects that stdout is not interactive, strips colour codes from output.

### Actual Behavior

step-ca does not detect that stdout is not interactive, includes colour codes, making logs very hard to read

### Additional Context

I can work around the problem by setting up the NAS with SSH and using docker logs, but it'd still be nice if the step-ca binary accepted an environment variable to control emitting colours; I could then configure the docker env variables to set that variable.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment] 2023-09-26 19:14
Hi @cricalix, I'm not able to reproduce this, on my docker the terminal is properly NOT detected and colors are disabled, but I've added support for the NO_COLOR environment variable here https://github.com/smallstep/certificates/pull/1559

**Comment by maraino** [comment] 2023-09-26 19:21
Fixed by https://github.com/smallstep/certificates/pull/1559. Now the environment variable NO_COLOR can be set to disable colors.

**Closed by maraino** 2023-09-26 19:21 UTC
Labels: bug, needs triage

**Comment by cricalix** [comment] 2023-09-28 05:50
Thank you @maraino . It's possible that Synology's docker integration is a bit weird, and pretends to be a tty, but with NO_COLOR support I can at least pass that through once the docker image gets your patch.

**Comment by maraino** [comment] 2023-09-29 00:23
> Thank you @maraino . It's possible that Synology's docker integration is a bit weird, and pretends to be a tty, but with NO_COLOR support I can at least pass that through once the docker image gets your patch.

It should be already in `smallstep/step-ca:0.25.0`
