### ISSUE TITLE
[Bug]: CGO build fails for arm64

### ISSUE THREAD

**Issue by einalex** [smallstep/certificates#1438] opened 2023-06-18 12:35 UTC
### Steps to Reproduce

`env CGO_ENABLED=1 GOOS=linux GOARCH=arm64 make build`

### Your Environment

* OS - current Arch linux
* `step-ca` Version - Smallstep CA/0.24.2-dev (linux/arm64)

### Expected Behavior

builds without problems

### Actual Behavior

```
runtime/cgo
# runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:30: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:34: Error: operand size mismatch for `mov'
gcc_arm64.S:36: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:39: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:42: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:45: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:48: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:52: Error: operand size mismatch for `mov'
gcc_arm64.S:53: Error: operand size mismatch for `mov'
gcc_arm64.S:54: Error: operand size mismatch for `mov'
gcc_arm64.S:56: Error: no such instruction: `blr x20'
gcc_arm64.S:57: Error: no such instruction: `blr x19'
gcc_arm64.S:59: Error: no such instruction: `ldp x27,x28,[sp,'
gcc_arm64.S:62: Error: no such instruction: `ldp x25,x26,[sp,'
gcc_arm64.S:65: Error: no such instruction: `ldp x23,x24,[sp,'
gcc_arm64.S:68: Error: no such instruction: `ldp x21,x22,[sp,'
gcc_arm64.S:71: Error: no such instruction: `ldp x19,x20,[sp,'
gcc_arm64.S:74: Error: no such instruction: `ldp x29,x30,[sp],'
make: *** [Makefile:74: bin/step-ca] Error 1
```

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tashian** [comment] 2023-06-20 22:19
Could you elaborate a bit more on your operating environment?
I was not able to reproduce this issue.

I built on:
- an arm64 Mac, but targeting GOOS `linux`.
- a Raspberry Pi 4
- an AWS Graviton instance

I ran the following:

```
sudo apt install make
curl -LO https://go.dev/dl/go1.20.5.linux-arm64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.5.linux-arm64.tar.gz
git clone https://github.com/smallstep/certificates
echo "export PATH=\$PATH:/usr/local/go/bin" >> .bashrc
source .bashrc
cd certificates
make bootstrap
env CGO_ENABLED=1 GOOS=linux GOARCH=arm64 make build
```

**Comment by einalex** [comment] 2023-06-20 22:36
Hi @tashian 
I'm building on an up to date amd64 arch linux box.

**Comment by einalex** [comment] 2023-06-20 22:54
@tashian compiling HEAD works fine.

**Comment by einalex** [comment] 2023-06-20 22:59
@tashian ah no. sorry.
the Makefile overrides the CGO_ENABLED=1 parameter. if you modify it so that it does build the CGO version, the build fails again.

can you make sure you are actually building CGO?

**Comment by tashian** [comment] 2023-06-20 23:16
@einalex Instead of modifying the Makefile, could you try following the [instructions for building `step-ca` with CGO](https://github.com/smallstep/certificates/blob/master/CONTRIBUTING.md#build-step-ca-using-cgo) and let me know if you're still experiencing this issue?

Thanks

**Comment by einalex** [comment] 2023-06-21 07:13
Hi @tashian 
I did that initially, but whenever the build works, running my config file returns this:

`unsupported kms type 'yubikey': step-ca is compiled without cgo or YubiKey support`

**Comment by tashian** [comment] 2023-06-21 19:21
Ahh. Okay, I am able to reproduce the issue now. Thank you.

**Comment by tashian** [comment] 2023-06-21 19:55
Okay. I think I found the issue.
You need both the `gcc` and `pkg-config` commands available on your system to build with cgo enabled.
Otherwise, the `go` command will fall back to not building with cgo.
The fallback appears to be a more recent feature in `go`.
I'll update the Makefile so that a proper error is displayed in this situation.

**Comment by einalex** [comment] 2023-06-21 21:24
I do have both, but I will try your changes.

**Comment by tashian** [comment] 2023-06-21 21:45
Hmm.
Yeah, in that case, I'm stumped on this one.
Might be an interoperability issue between cgo and your gcc?

**Comment by einalex** [comment] 2023-06-21 21:49
no idea.
my gcc version is (GCC) 13.1.1 20230429

**Comment by einalex** [comment] 2023-06-21 21:50
could you upload a compiled arm64 version with yubikey support?

**Comment by tashian** [comment] 2023-06-21 21:54
Unfortunately, we don't distribute cgo binaries as part of our release process, but if you go to our [step-ca docker image](https://hub.docker.com/r/smallstep/step-ca) and get an image with the tag `hsm`, you could copy the binary out of that image.

Or, start up a VM somewhere that you can use to build the image. There are full instructions for Ubuntu in [this blog post](https://smallstep.com/blog/build-a-tiny-ca-with-raspberry-pi-yubikey/).

I'm going to close this issue for now, but feel free to reopen it if this solution doesn't work for you.

**Closed by tashian** 2023-06-21 21:54 UTC
Labels: bug, needs triage
