### ISSUE TITLE
tls-alpn uses hardcoded port 443 instead of --tlsport

### ISSUE THREAD

**Issue by pturbing** [smallstep/certificates#219] opened 2020-03-27 10:17 UTC
Hey,

I'm testing out the tls-alpn challenge on localhost. Due to low privileges I'm spawning higher TLS challenge ports but the server is trying to connect back to 443 every time resulting in timeouts.

https://github.com/smallstep/certificates/blob/2c747fc11f8359f84de04da6940814133ad693d4/acme/challenge.go#L393

**Comment by mmalone** [comment] 2020-03-31 19:01
The [spec for the ALPN challenge extension](https://tools.ietf.org/html/rfc8737) states that the ACME server's connection "MUST use TCP port 443". So this is by design. Before we allow an override we need a review of security considerations. My first thought is that restricting to port 443 makes it easier for server admins to control who can get a cert (you can only get a cert if you can run a process that listens on port 443). But I want to make sure we fully understand the rationale behind this restriction before breaking spec.

For reference, this came up in another issue over here: https://github.com/smallstep/cli/issues/225.

**Comment by dopey** [comment] 2020-05-27 17:49
I'm going to close this issue for the time being, however if anyone would like to discuss further please comment and we'll re-open.

**Closed by dopey** 2020-05-27 17:49 UTC
Labels: more info needed
