### ISSUE TITLE
ACME rejectedIdentifier 

### ISSUE THREAD

**Issue by kmorkans** [smallstep/certificates#704] opened 2021-09-16 16:35 UTC
### Issue
{\"type\":\"urn:ietf:params:acme:error:rejectedIdentifier\",\"detail\":\"The server will not issue certificates for the identifier\"}}"

ACME broke after upgrading to version 0.17.2 (Helm chart 1.17.3)
Version 0.16.0 (Helm chart 1.16.1) works

### Environment
All K8s clusters 1.21.1
cert-manager v1.5.3 with internal intermediary CA
step clusterissuers

###Full log
```
{"duration":"44.102µs","duration-ns":44102,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"GET","msg":"","name":"ca","path":"/acme/acme/directory","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj9178g","response":"{\"newNonce\":\"https://some.internal.domain/acme/acme/new-nonce\",\"newAccount\":\"https://some.internal.domain/acme/acme/new-account\",\"newOrder\":\"https://some.internal.domain/acme/acme/new-order\",\"revokeCert\":\"https://some.internal.domain/acme/acme/revoke-cert\",\"keyChange\":\"https://some.internal.domain/acme/acme/key-change\"}","size":302,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"4.391553ms","duration-ns":4391553,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"HEAD","msg":"","name":"ca","nonce":"WEZYSGpMWXk4Y2h5bVRkWEo3eGZDSFdYeEhCOFpNQTQ","path":"/acme/acme/new-nonce","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj91790","size":0,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"9.002719ms","duration-ns":9002719,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"NU5lcGlVWVY3dVZpMlpRR2s3MzdPTFBFTkx3TFN5dzY","path":"/acme/acme/new-account","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj9179g","response":"{\"contact\":[\"mailto:dev@lumoa.me\"],\"status\":\"valid\",\"orders\":\"https://some.internal.domain/acme/acme/account/5qtm64Xp1Ey4v2SjrfeqzEb0LrHOd2Jj/orders\"}","size":147,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"7.581537ms","duration-ns":7581537,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"dWdtejJtRENibzFtOWo5bHp6Mjh1dzMybGhDUkRURjE","path":"/acme/acme/new-account","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917a0","response":"{\"contact\":[\"mailto:dev@lumoa.me\"],\"status\":\"valid\",\"orders\":\"https://some.internal.domain/acme/acme/account/5qtm64Xp1Ey4v2SjrfeqzEb0LrHOd2Jj/orders\"}","size":147,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"64.103µs","duration-ns":64103,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"GET","msg":"","name":"ca","path":"/acme/acme/directory","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917ag","response":"{\"newNonce\":\"https://some.internal.domain/acme/acme/new-nonce\",\"newAccount\":\"https://some.internal.domain/acme/acme/new-account\",\"newOrder\":\"https://some.internal.domain/acme/acme/new-order\",\"revokeCert\":\"https://some.internal.domain/acme/acme/revoke-cert\",\"keyChange\":\"https://some.internal.domain/acme/acme/key-change\"}","size":302,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"3.871623ms","duration-ns":3871623,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"HEAD","msg":"","name":"ca","nonce":"T1R6YUt6dlRRcUR5RnBUeDBiQXMzeHl6ZFVTNU9sZHk","path":"/acme/acme/new-nonce","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917b0","size":0,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"8.246375ms","duration-ns":8246375,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"ajVRYndiNUUyQ3l5SjdaRmtUbEFwZjRuWlc2TFNxSGU","path":"/acme/acme/new-account","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917bg","response":"{\"contact\":[\"mailto:dev@lumoa.me\"],\"status\":\"valid\",\"orders\":\"https://some.internal.domain/acme/acme/account/5qtm64Xp1Ey4v2SjrfeqzEb0LrHOd2Jj/orders\"}","size":147,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"36.159483ms","duration-ns":36159483,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"OFpuZE4yS2xOOWh1d3BEMkUzRmdPcklxbzJqbzAyQ0I","path":"/acme/acme/new-order","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917c0","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":201,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"7.894855ms","duration-ns":7894855,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"VzU2TFAxWldGRFZkQWlVSHc3VUcwcEZDeFIyWXpGTG0","path":"/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917cg","response":"{\"identifier\":{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"},\"status\":\"pending\",\"challenges\":[{\"type\":\"dns-01\",\"status\":\"pending\",\"token\":\"bPUnmvPUzrRAJnH5cTnrBqrtic1hfzOZ\",\"url\":\"https://some.internal.domain/acme/acme/challenge/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d/bgyfmohhX36z2Gcc98Y5gsBFDCfc39iK\"},{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bPUnmvPUzrRAJnH5cTnrBqrtic1hfzOZ\",\"url\":\"https://some.internal.domain/acme/acme/challenge/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d/Vhmb7Agczj7s76jPqp3I4paR6cwNPqsK\"},{\"type\":\"tls-alpn-01\",\"status\":\"pending\",\"token\":\"bPUnmvPUzrRAJnH5cTnrBqrtic1hfzOZ\",\"url\":\"https://some.internal.domain/acme/acme/challenge/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d/ne9qe4tJneevNGmqNJjIEYrGRR7DzBBe\"}],\"wildcard\":false,\"expires\":\"2021-09-17T15:47:57Z\"}","size":749,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"11.255948ms","duration-ns":11255948,"fields.time":"2021-09-16T15:47:57Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"NkZaYTV6Y3BSV09SaWlOWmlvNDBjeXdNWFpBV01EWnU","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebe3ffelksj917d0","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:57Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"4.607265ms","duration-ns":4607265,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"HEAD","msg":"","name":"ca","nonce":"czdCdUo5bHp3UEZKQW5LSGRCazlQZHhvTU15bmVuOGo","path":"/acme/acme/new-nonce","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917dg","size":0,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"13.578082ms","duration-ns":13578082,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"NG1nSzJ3Y1liS0lvMWlPd0E0T0pyNDZuVFZNME9oNXQ","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917e0","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"139.878356ms","duration-ns":139878356,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"SldRd1ZTZWNRdXZkWnVjejZ0TllxbmpNZTEwcjM1WDA","path":"/acme/acme/challenge/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d/Vhmb7Agczj7s76jPqp3I4paR6cwNPqsK","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917eg","response":"{\"type\":\"http-01\",\"status\":\"invalid\",\"token\":\"bPUnmvPUzrRAJnH5cTnrBqrtic1hfzOZ\",\"url\":\"https://some.internal.domain/acme/acme/challenge/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d/Vhmb7Agczj7s76jPqp3I4paR6cwNPqsK\",\"error\":{\"type\":\"urn:ietf:params:acme:error:rejectedIdentifier\",\"detail\":\"The server will not issue certificates for the identifier\"}}","size":334,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"12.4µs","duration-ns":12400,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"GET","msg":"","name":"ca","path":"/health","protocol":"HTTP/2.0","referer":"","remote-address":"10.6.1.0","request-id":"c51mebm3ffelksj917fg","size":16,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"kube-probe/1.21","user-id":""}
{"duration":"9.2µs","duration-ns":9200,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"GET","msg":"","name":"ca","path":"/health","protocol":"HTTP/2.0","referer":"","remote-address":"10.6.1.0","request-id":"c51mebm3ffelksj917g0","size":16,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"kube-probe/1.21","user-id":""}
{"duration":"8.881012ms","duration-ns":8881012,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"MmFNTEhLcjZSTmlLR2duVTkxS0M1MHF5cWZDeTF3Wjc","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917f0","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"9.134426ms","duration-ns":9134426,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"RmV3TFBreHJkbUNuaTJlMkdieWR5VXQzZUhpMWFXWTU","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917gg","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"8.598695ms","duration-ns":8598695,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"Z2VvRVVNSXN4aFdTc29mMzRnVkdPUEhvVjIzcllUdUY","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917h0","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"8.708801ms","duration-ns":8708801,"fields.time":"2021-09-16T15:47:58Z","level":"info","method":"POST","msg":"","name":"ca","nonce":"TVYwdGFPUXc5ZHhTbUhvMmZqRURVRXhPa3U1QTluR2g","path":"/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9","protocol":"HTTP/1.1","referer":"","remote-address":"10.6.0.159","request-id":"c51mebm3ffelksj917hg","response":"{\"id\":\"oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9\",\"status\":\"pending\",\"expires\":\"2021-09-17T15:47:57Z\",\"identifiers\":[{\"type\":\"dns\",\"value\":\"argo-test.hq.lumoa.me\"}],\"notBefore\":\"2021-09-16T15:46:57Z\",\"notAfter\":\"2021-10-17T01:47:57Z\",\"authorizations\":[\"https://some.internal.domain/acme/acme/authz/cIzEeKPGeOMRObPZ6TxFSGdAL4eqey7d\"],\"finalize\":\"https://some.internal.domain/acme/acme/order/oolYZNVcRPnZupSdaTbrk4OCqJNJjwT9/finalize\"}","size":417,"status":200,"time":"2021-09-16T15:47:58Z","user-agent":"cert-manager/v1.5.3 (clean) golang.org/x/crypto/acme","user-id":""}
{"duration":"15.4µs","duration-ns":15400,"fields.time":"2021-09-16T15:48:08Z","level":"info","method":"GET","msg":"","name":"ca","path":"/health","protocol":"HTTP/2.0","referer":"","remote-address":"10.6.1.0","request-id":"c51mee63ffelksj917i0","size":16,"status":200,"time":"2021-09-16T15:48:08Z","user-agent":"kube-probe/1.21","user-id":""}
```

**Comment by maraino** [comment] 2021-09-16 17:24
According to the logs, it's an `http-01` challenge, and the only place I see that this error occurs in this challenge is this line:
https://github.com/smallstep/certificates/blob/8df9f629b173182eb9c73768c87b377cb4f56d53/acme/challenge.go#L103-L106

Unfortunately, the received and expected values are not in the logs. That condition is comparing the request body with the string "<token>.<key-thumprint>". 

I know of a change in the latest version of `go-jose` that would change the thumbprint of an Ed25519 key, but I see neither certificates nor cert-manager using the latest version yet. Do you have access to the account key?

If you do, and if it's an Ed25519 key (`okp`) can you provide the public key (`x`) and the key id (`kid`)?

**Comment by kmorkans** [comment] 2021-09-16 18:25
@maraino You'll have to give me more details on how to retrieve the public key and the key id you need.

**Comment by maraino** [comment] 2021-09-16 18:37
According to cert-manager docs there's a secret that contains the key, for example in this case `example-issuer-account-key`

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: user@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
```

If the key is in PEM format, you should only post here the public one, to get the JWK version where you can see the type and `x` you can do this:

```
step crypto key format --jwk --no-password --insecure mykey.pem
```
or extract the key like this:
```
step crypto key public mykey.pem
```

**Comment by myokoyama28** [comment] 2021-09-21 08:45
I faced the same error.
In my case, I was able to generate a certificate first time but failed to renew the certificate with the same error message.

Environment:
- kubernetes: v1.20.8
- cert-manager: v1.4.0
- step-ca: v0.17.2

It seems that the error occurs from v0.17.1.
I think it might be caused by the changes of https://github.com/smallstep/certificates/pull/557.
Reverting the changes, I was able to generate and renew certificates correctly.

**Comment by maraino** [comment] 2021-09-22 20:19
Hi @kmorkans @myokoyama28 I'm trying to reproduce with no luck this issue using the following configuration:

* kubernetes: v1.21.3
* step-certificates helm chart: v1.17.2  (step-ca v0.17.2(
* cert-manager: v1.5.3

My acme-issuer looks like this:

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme-issuer
spec:
  acme:
    email: mariano@smallstep.com.com
    server: https://step-certificates.default.svc.cluster.local/acme/acme/directory
    skipTLSVerify: true
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
```

Can you give us more information, how do your issuer and certificate look like? What type of account key are you using?  On which environment you're running this, eg: minikube, docker for desktop, GKE, EKS, RKE, microk8s, ...? Or anything else that can be relevant

To know the type of key you can check at the first line of this (acme-account-key is the one referenced in the YAML above):
```
kubectl -n cert-manager get secrets acme-account-key -o json | jq -r '.data["tls.key"]'  | base64 -d | step crypto key inspect | head
```

**Comment by myokoyama28** [comment] 2021-09-27 05:04
My issuer is almost the same. But the kind is `Issuer` and I add `enableDurationFeature: true`.
My certificate looks like this:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  duration: 1h
  renewBefore: 57m
  secretName: test-cert-tls
  issuerRef:
    name: issuer
    kind: Issuer
  dnsNames:
  - xxxx
```
The type of account key is `RSA Private-Key: (2048 bit)`.

**Comment by maraino** [comment] 2021-09-27 19:14
@myokoyama28 I'm not able to reproduce the error with your configuration (Issuer/enableDurationFeature, duration ...)

And the only way in the code I see to get this error for RSA keys is that at some point the account key changed.
```json
{
    "type":"urn:ietf:params:acme:error:rejectedIdentifier",
    "detail":"The server will not issue certificates for the identifier"
}
```

**Comment by myokoyama28** [comment] 2021-09-30 09:27
@maraino 
I found that the error was due to my backend application.
The application returned `200` against all requests to any paths (including /.well-known/acme-challenge/...).
It also returned `200` when the challenge was not set.
So the validation failed and the error seemed to occur.
Sorry for my misunderstanding.
Thank you for your polite support.

**Comment by maraino** [comment] 2021-10-01 01:04
@kmorkans I'm closing this issue because we're not able to reproduce it. If you can reproduce it, please add more information and feel free to re-open it.

**Closed by maraino** 2021-10-01 01:04 UTC
Labels: bug

**Comment by dopey** [comment] 2021-10-22 04:51
No problem. Let us know what you find.
